// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJfCjL_2CwZkmfzA6bpB20StCVkH7Svgw',
    appId: '1:946347091274:web:bd3c32eaa36edad5fa0db3',
    messagingSenderId: '946347091274',
    projectId: 'qubiq-admin-93bf2',
    authDomain: 'qubiq-admin-93bf2.firebaseapp.com',
    storageBucket: 'qubiq-admin-93bf2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNprEmtQ-jwLGTQmOXCn0erRM5K9Jnrxg',
    appId: '1:946347091274:android:25efbbd70f7aae89fa0db3',
    messagingSenderId: '946347091274',
    projectId: 'qubiq-admin-93bf2',
    storageBucket: 'qubiq-admin-93bf2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7qJlGuycHuDSLuI_URcewdR6y5exxjxE',
    appId: '1:946347091274:ios:b92764c8e2c91461fa0db3',
    messagingSenderId: '946347091274',
    projectId: 'qubiq-admin-93bf2',
    storageBucket: 'qubiq-admin-93bf2.firebasestorage.app',
    iosBundleId: 'com.example.emmiManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7qJlGuycHuDSLuI_URcewdR6y5exxjxE',
    appId: '1:946347091274:ios:b92764c8e2c91461fa0db3',
    messagingSenderId: '946347091274',
    projectId: 'qubiq-admin-93bf2',
    storageBucket: 'qubiq-admin-93bf2.firebasestorage.app',
    iosBundleId: 'com.example.emmiManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJfCjL_2CwZkmfzA6bpB20StCVkH7Svgw',
    appId: '1:946347091274:web:fb008cbd6a022498fa0db3',
    messagingSenderId: '946347091274',
    projectId: 'qubiq-admin-93bf2',
    authDomain: 'qubiq-admin-93bf2.firebaseapp.com',
    storageBucket: 'qubiq-admin-93bf2.firebasestorage.app',
  );
}
